# Generated by Django 3.1.7 on 2021-04-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spell_school',
            options={'verbose_name': 'Spell school', 'verbose_name_plural': 'Spell schools'},
        ),
    ]
