# Generated by Django 3.1.7 on 2021-04-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0002_auto_20210406_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('spell_level', models.CharField(choices=[(0, 'sztuczka'), (1, '1. krąg'), (2, '2. krąg'), (3, '3. krąg'), (4, '4. krąg'), (5, '5. krąg'), (6, '6. krąg'), (7, '7. krąg'), (8, '8. krąg'), (9, '9. krąg')], default=0, max_length=1)),
            ],
        ),
    ]
