# Generated by Django 3.1.7 on 2021-04-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0004_auto_20210406_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='casting_time',
            field=models.IntegerField(choices=[(1, '1 akcja'), (2, '1 akcja dodatkowa'), (3, 'reakcja'), (4, '1 minuta'), (5, '10 minut'), (6, '1 godzina'), (7, '8 godzin'), (8, '12 godzin'), (9, '24 godziny')], default=1),
        ),
        migrations.AddField(
            model_name='spell',
            name='concentration',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='distance',
            field=models.CharField(default='dotyk', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.IntegerField(choices=[(10, 'natychmiastowy'), (12, '1 runda'), (4, '1 minuta'), (5, '10 minut'), (6, '1 godzina'), (7, '8 godzin'), (9, '24 godziny'), (15, '10 dni'), (16, '30 dni'), (17, 'specjalny'), (11, 'do rozproszenia')], default=1),
        ),
        migrations.AddField(
            model_name='spell',
            name='higher_level',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='material',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='material_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='spell',
            name='ritual',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='somatic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spell.spell_school'),
        ),
        migrations.AddField(
            model_name='spell',
            name='verbal',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
