# Generated by Django 3.1.7 on 2021-04-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0005_auto_20210406_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='distance',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
