# Generated by Django 3.1.7 on 2021-04-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0007_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.ManyToManyField(blank=True, to='spell.Components'),
        ),
    ]
