# Generated by Django 3.1.7 on 2021-04-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0008_spell_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='material',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='somatic',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='verbal',
        ),
    ]
