# Generated by Django 3.1.7 on 2021-04-15 19:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0009_auto_20210410_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
